.readthedocs.yml, CHANGELOG.md, README.md, docs/source/conf.py
https://py-pdf-parser.readthedocs.io/en/latest/
=> Host documentation on readthedocs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CONTRIBUTING.md
=> Add issue templates

CHANGELOG.md, py_pdf_parser/components.py, py_pdf_parser/filtering.py, py_pdf_parser/tests/test_filtering.py
Closes https://github.com/jstockwin/py-pdf-parser/issues/64
=> [filtering] Cache filtering by fonts

CHANGELOG.md, py_pdf_parser/components.py, py_pdf_parser/tests/test_filtering.py
Fixed a bug where filtering by font was broken.
Closes #77
=> [components] Fix broken element_indexes_with_fonts method

.github/workflows/continuous-integration.yml
Runs tests, linting and docs in parallel.
None
**Testing**
N/A
**Checklist**
=> [meta] Run github actions steps in parallel

.github/workflows/release.yml
This github action will run whenever we publish a new release. It will push the dockerfile to dockerhub, and build + check the package and push to PyPI.
Credentials are taken from secrets, which I've added.
Closes #79
=> [meta] Add github action to publish all releases to pypi and dockerhub

CHANGELOG.md, py_pdf_parser/visualise/sections.py
First checks if we can draw a simple rectangle around a section (with increasingly smaller margins). If we can't (because there will always be an element that is NOT in the section that would be in the rectangle), then the old behaviour using Voronoi diagrams will be used. The Voronoi diagram is only computed when needed.
This change involved a bit of a refactor where more data is stored on the class, rather than passing it between lots of functions.
Closes #72
**Testing**
This is been tested on a few example PDFs locally. Unfortunately we cannot easily write tests for the visualise tool.
**Checklist**
=> [visualise] Draw rectangular section outlines when possible

.github/workflows/release.yml
Fixes some small issues when publishing the release to PyPI automatically.
I've run it manually* for version `0.3.0`.
*By which I mean I changed the action to `on: ['push']` so it's been tested on the GitHub runner.
=> [meta] Fix release github workflow

CHANGELOG.md, py_pdf_parser/loaders.py, setup.py
Advanced layout analysis is not needed since we order text boxes ourselves, so we can disable it by default and hence improve the performance of the analysis.
Closes https://github.com/jstockwin/py-pdf-parser/issues/50
**Checklist**
=> Disable advanced layout analysis

CHANGELOG.md, py_pdf_parser/tables.py, tests/test_tables.py
This will add a flag to the table extraction functions to enable the removal of rows which are duplicats of the header row.
Closes https://github.com/jstockwin/py-pdf-parser/issues/76
**Testing**
Tests have been added to the table extraction tests to make sure the duplicate header rows are removed.
**Checklist**
=> [tables] Add flag to remove duplicate header rows

CHANGELOG.md, py_pdf_parser/sectioning.py, tests/test_sectioning.py
This adds a `__len__` and `__repr__` functions to the `Section` class.
Closes https://github.com/jstockwin/py-pdf-parser/issues/63
**Testing**
Tests were added to the section tests that make sure that calling `len()` and `repr()` on a section will return the expected results.
**Checklist**
=> Section repr

CHANGELOG.md, py_pdf_parser/filtering.py, tests/test_filtering.py
Caps the tolerance at half the width/height of the element, thus avoiding an invalid bounding box error.
Closes #102
**Testing**
CI Tests have been added
**Checklist**
=> [filtering] Cap tolerance at half the width/height of the element

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
I am adding all the GitHub standard labels, and so the ones in the issue
templates have changed. I will also lower-case all of our existing ones
for consistency.
See https://help.github.com/en/github/building-a-strong-community/encouraging-helpful-contributions-to-your-project-with-labels
=> [meta] Change GitHub Labels back to standards

CHANGELOG.md, py_pdf_parser/exceptions.py, py_pdf_parser/filtering.py, tests/test_filtering.py
Discussion in #111. Essentially, it was difficult to move through an element list starting at a given element. This makes that process both easier, and (I think) more efficient.
Closes #111
**Testing**
CI tests have been added.
**Checklist**
=> [filtering] Add new move_forwards_from and move_backwards_from functions

.github/dependabot.yml, CHANGELOG.md
Adds dependabot, to keep our packages up to date.
https://github.com/jstockwin/py-pdf-parser/issues/123 was caused by an out of date package, and this should solve that issue generally.
**Testing**
N/A
**Checklist**
=> [meta] Enable dependabot package updates

.github/workflows/continuous-integration.yml
Currently there are issues with multiple builds running at the same time picking up the wrong cached container. This should hopefully resolve that.
=> Simplify GitHub actions

CHANGELOG.md, py_pdf_parser/loaders.py
Ensures only `LTTextBoxes` get through as our `elements`. See #154 for details.
Closes #154
**Testing**
I have tested this on my broken pdf, and CI tests should still pass.
**Checklist**
=> [loaders] Only accept LTTextBoxes from pdfminer.six

.github/workflows/continuous-integration.yml
Some PRs from other authors are failing CI due to not authenticating with the docker repo. This was needed as we used the "build with cache", which pushed and pulled partial images. I have now removed this.
None
**Testing**
CI will pass
**Checklist**
=> [github-actions] Update CI workflow to avoid login issues

.readthedocs.yml, CHANGELOG.md
This upgrades the python version in the `.readthedocs.yml` file from Python 3.6 to 3.8. This is required as building the docs is currently failing because some of the requirements can't be installed in Python 3.6.
**Checklist**
=> [readthedocs] Bump python version from 3.6 to 3.8

.github/workflows/release.yml
This was from when we used to publish docker images, which we no longer do.
=> [meta] Remove unnecessary tag in release workflow

py_pdf_parser/loaders.py
Fix broken URL (https://pdfminersix.readthedocs.io/en/latest/api/composable.html#laparams) to instead point to https://pdfminersix.readthedocs.io/en/latest/reference/composable.html#laparams
**Testing**
None
**Checklist**
=> Update PDFMiners LAParams docs URL

docs/source/examples/order_summary.rst, docs/source/overview.rst
Updated the Order Summary example and Font Mapping Overview to calrify the usage of regey patterns as font mappings.
#237
=>  [docs] Clarify regex font mapping

.flake8, .pre-commit-config.yaml, py_pdf_parser/visualise/__init__.py, pytype.cfg, tests/test_visualise.py
Follows on from https://github.com/jstockwin/py-pdf-parser/pull/288
Use pre-commit.ci for linting. This will run automatically as it's installed as github app.
The [first pre-commit.ci run](https://results.pre-commit.ci/run/github/218796970/1646757035.Yi-MApXjT1WbIPTc3zezwA) failed due to unused imports, which is good.
Required checks will need to be updated before merging, but I'll wait for @paulopaixaoamaral to approve first.
=> Use pre-commit.ci for linting, add new linting checks

CHANGELOG.md, MANIFEST.in, setup.py
This change will remove tests and docs from binary distribution wheels (PyPi) and source distribution (sdist).
closes https://github.com/jstockwin/py-pdf-parser/issues/383
**Testing**
Run `python setup.py bdist_wheel` and confirm the tests directory is excluded from the generated wheel.
**Checklist**
=> Remove tests and docs from wheels
